### ISSUE TITLE
FVEAutunlock

### ISSUE THREAD

**Issue by MaxFuwin** [PowerShell/xBitlocker#57]
HI, 
My D,E,F Drives were all locked by the BitLocker. And I can't find any BitLocker Recovery Keys in my outlook account but Fortunately I found 3 Autounlock keys in registry in hex.But they are encrypted. The location of key is  "HKLM/SYSTEM/CurrentControlSet/Control/FVEAutoUnlock/{guids}"

Here is the key:
70 00 00 00 09 00 00 00 1E A6 AD C1 9C 9B EB 45
BE 33 C6 CF 85 63 FA 11 E0 C6 B3 8E 20 31 D7 01
50 00 00 00 05 00 01 00 8F E7 B3 8E 20 31 D7 01
01 00 00 10 9D E4 55 A5 E5 1F 94 60 34 CF FD F5
87 75 E6 92 13 28 EC E7 D2 E2 98 5F 36 EF D4 27
75 91 BA B5 73 AC 0D 6D 09 E2 56 64 68 05 12 B3
4D 4B 8B FE B8 C8 81 94 50 1D 33 BC D9 01 B8 98

and this:
70 00 00 09 00 00 00 D7 EE 68 71 F2 72 89 40 B5
94 F6 A3 F2 CC 39 4E 10 4B EA 8F 20 31 D7 01 50
00 00 00 05 00 01 00 12 54 EA 8F 20 31 D7 01 02
00 00 10 C5 EF 06 D6 6B E9 CD 19 B4 86 7A 89 74
D8 48 41 93 B7 DE 17 28 8D DD 48 55 7F E6 11 2D
E1 03 57 BC 01 DC 8F E8 B9 30 B8 9F E0 E1 1B F5
22 67 1A 7A D8 74 2A A1 82 7C DC 10 4A E1 B8

and this:
70 00 00 00 09 00 00 00 CA F1 B9 14 FC DE 80 4F
BD 03 65 92 D6 E9 DA EC 60 84 13 8D 20 31 D7 01
50 00 00 00 05 00 01 00 CA 31 15 8D 20 31 D7 01
00 00 00 10 0E 6A 32 0E 2D 37 BE A8 1A 76 69 C5
7D 50 32 09 53 FF E7 68 E4 4D A9 19 06 56 E4 1E
A3 9D 8E 6A 27 FE 36 ED 6B 03 1A 2D F8 57 DE 11
C0 69 D0 9E 48 A3 67 20 94 BB CF C9 C4 89 9B D2

Can you please help me to decrypt those keys? 

MaxFuwin

**Comment by johlju** [comment]
Sorry to hear this, but this is out of scope for this repository. Suggest calling Microsoft support. But since the encryption is used on device there isn't much to do without you having the recovery keys (the whole point with BitLocker is to not be able to access information without the proper information). 

I'm closing this issue at this time since this is not something we can help with here.
